### ISSUE TITLE
Readme Discussion

### ISSUE THREAD

**Issue by MikaylaRay44** [alis0nc/kuthesis#13]
So I know that in my pull request for the readme update I outlined the fact that there are 4 types of theses. There aren't a ton of differences between them, but I would like to raise the question now whether or not there can be optional sections in a LaTex document? If so then all of it can be done in one as things like appendices are optional but very important to some people (like me!). There are also things exclusive to some thesis types, like a  Business Plan for E-ship theses.

Let me know your thoughts I'd love to help out, but my contributions will be limited as I am busy working on my own thesis as well.

**Comment by alis0nc** [comment]
Cross referencing this to #12

**Comment by alis0nc** [comment]
Better docs merged in 71139c0
